---
# This playbook deploys DC/OS

- name: apply common configuration to all nodes
  hosts: all
  serial: 10
  become: true

  roles:
    - common

- name: generate the DC/OS configuration
  hosts: workstations
  serial: 10
  become: true

  roles:
    - workstation

- name: deploy DC/OS
  hosts: [ masters, agents, agents_public]
  serial: 10
  become: true

  roles:
    - node

- name: Cleanup workstations
  hosts: workstation
  serial: 10
  become: true

  roles:
    - workstation-cleanup

- debug: msg="FINISHED! DC/OS UI can be now accessed by typing in one of the master IPs into the browser. To visit the ZooKeeper exhibitor in your browser, type `<master-IP>/exhibitor`." verbosity=0
